apiVersion: v1
kind: Service
metadata:
    name: servicefirst
spec:
    type: NodePort
    ports:
       - targetPort: 80
         port: 80
         nodePort: 30008
    selector:
         type: newapp